# Generated by Django 3.1.1 on 2020-09-26 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import items.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', items.fields.OrderField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'order'],
            },
        ),
    ]
